/*
SELECT 
	t.SCHEMA_NAME
FROM 
	[INFORMATION_SCHEMA].SCHEMATA t
WHERE
	t.SCHEMA_NAME NOT LIKE 'db[_]%' AND
	t.SCHEMA_NAME NOT IN('guest', 'INFORMATION_SCHEMA', 'sys')
*/
IF OBJECT_ID('tempdb..#Schema') IS NOT NULL DROP TABLE #Schema
SELECT DISTINCT SCHEMA_NAME = t.TABLE_SCHEMA
INTO #Schema
FROM 
	[INFORMATION_SCHEMA].TABLES t
WHERE
	t.TABLE_SCHEMA <> 'DBTimeLine'

IF OBJECT_ID('tempdb..#Table') IS NOT NULL DROP TABLE #Table
SELECT 
	TABLE_NAME,
	TABLE_SCHEMA
INTO #Table
FROM 
	[INFORMATION_SCHEMA].TABLES t
WHERE 
	t.TABLE_TYPE = 'BASE TABLE' AND
	t.TABLE_SCHEMA <> 'DBTimeLine'

IF OBJECT_ID('tempdb..#TableColumn') IS NOT NULL DROP TABLE #TableColumn
SELECT 
	c.COLUMN_NAME,
	c.TABLE_NAME,
	c.TABLE_SCHEMA,
	c.ORDINAL_POSITION,
	c.COLUMN_DEFAULT,
	c.IS_NULLABLE,
	c.DATA_TYPE,
	c.CHARACTER_MAXIMUM_LENGTH,
	c.NUMERIC_PRECISION,
	c.NUMERIC_SCALE
INTO #TableColumn
FROM 
	[INFORMATION_SCHEMA].Columns c
	INNER JOIN #Table t ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME

IF OBJECT_ID('tempdb..#View') IS NOT NULL DROP TABLE #View
SELECT 
	VIEW_NAME = t.TABLE_NAME,
	t.TABLE_SCHEMA,
	t.VIEW_DEFINITION
INTO #View
FROM
	[INFORMATION_SCHEMA].VIEWS t

IF OBJECT_ID('tempdb..#TablePrimaryKey') IS NOT NULL DROP TABLE #TablePrimaryKey
SELECT
	PK_CONSTRAINT_NAME = t.CONSTRAINT_NAME,
	t.TABLE_NAME,
	t.TABLE_SCHEMA
INTO #TablePrimaryKey
FROM
	[INFORMATION_SCHEMA].TABLE_CONSTRAINTS t
WHERE 
	t.CONSTRAINT_TYPE = 'PRIMARY KEY'

IF OBJECT_ID('tempdb..#TableForeignKey') IS NOT NULL DROP TABLE #TableForeignKey
SELECT
	FK_CONSTRAINT_NAME = t.CONSTRAINT_NAME,
	t.TABLE_NAME,
	t.TABLE_SCHEMA
INTO #TableForeignKey
FROM
	[INFORMATION_SCHEMA].TABLE_CONSTRAINTS t
WHERE 
	t.CONSTRAINT_TYPE = 'FOREIGN KEY'

SELECT
	fk.FK_CONSTRAINT_NAME,
	FK_TABLE_NAME = fk.TABLE_NAME,
	FK_TABLE_SCHEMA = fk.TABLE_SCHEMA
, *	
FROM
	[INFORMATION_SCHEMA].REFERENTIAL_CONSTRAINTS t
	LEFT JOIN #TablePrimaryKey pk ON t.UNIQUE_CONSTRAINT_NAME = pk.PK_CONSTRAINT_NAME
	LEFT JOIN #TableForeignKey fk ON t.CONSTRAINT_NAME = fk.FK_CONSTRAINT_NAME
SELECT 
*	
FROM
	[INFORMATION_SCHEMA].KEY_COLUMN_USAGE
SELECT * FROM #Schema
SELECT * FROM #Table
SELECT * FROM #TableColumn
SELECT * FROM #TablePrimaryKey
SELECT * FROM #View

